data:
  APP_KEY: YmFz#
  DB_PASSWORD: QXBo23ZGl#
  DB_USERNAME: YXBwd
  HORIZON_BASIC_AUTH_PASSWORD: QGNjRS
  MAIL_PASSWORD: YmwxMjM
  MAIL_USERNAME: YmFuZ2x
  MYBLAPI_REPORT_KEY: c2Zk#
  MYBLAPI_REPORT_SECRET: YmFi#
  RABBITMQ_PASSWORD: QGpGc240Q
  RABBITMQ_USER: cGF5bmc=
  REDIS_URL: cmVkaXM6L#
