data:
  mybl_private_key.pem: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcFFJQkFBS0NBUUVBMDRmWjgxRGVRbFJwQjFLZHRKRWFLOEJ6OXdSekZmcUlqTy8=
  mybl_public.pem: LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUEwNGZaODFEZVFsUnBCMUtkdEp==