{{- define "common.deployment-worker-stable" }}

{{- if hasKey .Values "deploymentWorkerStable"  }}
{{- $deploymentWorkerStableConfig := .Values.deploymentWorkerStable | default (dict "enabled" false) }}
{{- if $deploymentWorkerStableConfig.enabled }}


apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}-worker-deployment
  annotations:
    kubernetes.io/change-cause: {{ .Values.stable.image.tag }}
  labels:
  {{- include "applicationLable-worker-stable" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "applicationWorkerServiceLabelSelector" . | nindent 6 }}
  template:
    metadata:
      labels:
      {{- include "applicationWorkerServiceLabelSelector" . | nindent 8 }}
    spec:
    {{- if .Values.nodeSelector.enabled }}
      nodeSelector:
        {{ .Values.nodeSelector.label.key }}: {{ .Values.nodeSelector.label.value }}
    {{- end }}
      imagePullSecrets: 
      {{- range .Values.imagePullSecrets }}
        - name: {{ . }}
      {{- end }}
      volumes:
      {{- if .Values.vault.vaultsslsecret.enabled }}
      - name: {{ .Values.app.name }}-ssl-volume
        secret:
          defaultMode: 420
          secretName: {{ .Values.app.name }}-ssl-keys-secrets
      {{- end }}        
      {{- if .Values.phpfpmconf.enabled }}
      - name: {{ .Values.app.name }}-cm-phpfpmconf
        configMap:
          name: {{ .Values.app.name }}-cm-phpfpmconf
      {{- end }}
      {{- if .Values.nginxconf.enabled }}
      - name: {{ .Values.app.name }}-cm-nginxconf
        configMap:
          name: {{ .Values.app.name }}-cm-nginxconf
      {{- end }}      
      containers:
        - name: {{ .Values.app.name }}
          image: {{ .Values.stable.image.repository}}:{{ .Values.stable.image.tag }} 
          imagePullPolicy: {{ .Values.stable.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.container.port }}
          env:
          - name: type
            value: worker
          - name: image_tag
            value: {{ .Values.stable.image.tag }}
          envFrom:
            - configMapRef:
                name: {{ .Values.app.name }}-configmap
            - secretRef:
                name: {{ .Values.app.name }}-secrets
          volumeMounts:
          {{- if .Values.vault.vaultsslsecret.enabled }}
          - mountPath: {{ .Values.vault.vaultsslsecret.ssl_mount_path }}
            name: {{ .Values.app.name }}-ssl-volume
            readOnly: true
          {{- end }}  
          {{- if .Values.phpfpmconf.enabled }}
          - mountPath: /app/opt/php/etc/php-fpm.conf
            name: {{ .Values.app.name }}-cm-phpfpmconf
            readOnly: true
            subPath: php-fpm.conf
          {{- end }}
          {{- if .Values.nginxconf.enabled }}
          - mountPath: /app/opt/nginx/conf/nginx.conf
            name: {{ .Values.app.name }}-cm-nginxconf
            readOnly: true
            subPath: nginx.conf
          {{- end }}          
          resources:
            limits:
              cpu: {{ .Values.limits.cpu }}
              memory: {{ .Values.limits.memory }}
            requests:
              cpu: {{ .Values.requests.cpu }}
              memory: {{ .Values.requests.memory }}


  {{- end }}  
{{- end }}  


{{- end }}  