
# define template for secret config from file
{{- define "common.secret-confg-from-file" }}

{{- if hasKey .Values "secretConfgFromFile"  }}
{{- $secretConfig := .Values.secretConfgFromFile | default (dict "enabled" false) }}
{{- if $secretConfig.enabled }}

{{- $path := printf "config/%v/secret-config.yaml" .Values.env }}
{{- $secretsRaw := .Files.Get $path }}
{{- $secrets := fromYaml $secretsRaw }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.app.name }}-secrets
type: Opaque
data:
{{- range $key, $value := $secrets.data }}
  {{ $key }}: {{ $value | quote }}
{{- end }}

  {{- end }}  
{{- end }}  

{{- end }}  