# define template for service config from file
{{- define "common.service" }}

{{- if hasKey .Values "service"  }}
{{- $serviceConfig := .Values.service | default (dict "enabled" false) }}
{{- if $serviceConfig.enabled }}

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}-svc
spec:
  type: {{ .Values.service.type }}
  selector:
  {{- include "applicationServiceLabelSelector" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP

  {{- end }}  
{{- end }}  

{{- end }}        