{{- /*
This will generate SSL secret config
Maintainer: Arif Hossen
Change history:
20241016: Added Vault Definition
*/}}

{{- define "common.vault-static-ssl-secrets" }}

{{- if hasKey .Values "vault"  }}
{{- $checkValueConfig := .Values.vault | default (dict "enabled" false) }}
{{- if $checkValueConfig.enabled }}

---
{{- if hasKey .Values.vault "vaultsslsecret"  }}
{{- $checkValueVaultsslsecret := .Values.vault.vaultsslsecret | default (dict "enabled" false) }}
{{- if $checkValueVaultsslsecret.enabled }}

apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-{{ .Values.app.name }}-ssl-keys-secrets
spec:
  vaultAuthRef: vault-auth
  mount: {{ .Values.env}}
  type: kv-v2
  path:  {{ .Values.vault.vaultsslsecret.secretPath}}
  refreshAfter: {{ .Values.vault.vaultsslsecret.refreshAfter}}
  destination:
    create: true
    name: {{ .Values.app.name }}-ssl-keys-secrets

  {{- end }}      
{{- end }}      

  {{- end }}  
{{- end }}  

{{- end }}  