apiVersion: v2
name: common
description: A Helm common chart for Kubernetes, DPE, Banglalink
type: library
version: 0.1.26
# Maintainers section to include developer information
maintainers:
  - name: digital platform engineering team
    email: dpengineering@banglalink.net


# Optional: Add a section for change history
annotations:
  change-history: |
    - 0.1.0: Initial release of common chart.
    - 0.1.1: Added generic cronjob, additional cronjob template for ryze and added extend label information
    - 0.1.2: Add mount options in Generic CronJob for php-fpm.conf & nginx.conf \
              Update Generic Cronjob Template config for successfulJobsHistoryLimit and failedJobsHistoryLimit
    - 0.1.3: Add options to include Generic Worker Deployment with a Env Type and Value
    - 0.1.4: Add Default Conditon check for parameters value that don't exist in value file - vault, ingress, hpa, configmap
    - 0.1.5: Add condition for ssl in deployment
    - 0.1.6: Add option for cronjob in vaule file as an array/sequence 
    - 0.1.7: Add/Update name for Deployment Worker and Coronjob
    - 0.1.8: Add Job Definition, Add Service, Add Extra Label, Correct continer name for job and worker, add deployment extra env from value file
    - 0.1.9: Add add env as sequence for job, cronjob, deploymentwork and deployment; add command options for job, cronjob, deploymentwork and deployment; add one extra label workerdeployment; remove few old config template
    - 0.1.10: Add livenessProbe and readinessProbe, add new env with name APP_VERSION
    - 0.1.11: Correct Replicas for Deployment Worker
    - 0.1.12: Added missing loglabelindex for pod: loglabelindex: {{ .Values.app.name }}-{{ .Values.env }} \
              Correct Env mapping for job and cronjob
    - 0.1.13: Add option to disable port from value file
    - 0.1.14: Add Resource Requirement in individual configuration part (deployment/worker deployment/corn/cronjob) 
    - 0.1.15: Add Initcontainer to verify secrets with a config filed and move port definiton to respective section of deployment/depoloyment work/cronjob/job 
    - 0.1.16: Add ssl mount options for job & cronjob, added option to mount a configmap with a key  
    - 0.1.17: Add topologySpreadConstraints and nodeAffinity for traffic distribution
    - 0.1.18: Update restartPolicy for cronjob
    - 0.1.19: Add option to mount file in deployment worker
    - 0.1.20: Add nfs mount in deployment worker
    - 0.1.21: Add nfs mount in deployment stable
    - 0.1.22: Add file mount and nfs mount in both deployment stable and worker
    - 0.1.23: NFS Mount issue fix
    - 0.1.24: NFS Mount worker issue fix
    - 0.1.25: NFS Mount added in cronjob and job
    - 0.1.26: Host allias and custom dns configuration part added in the deployment, deployment worker, job and cronjob